/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedPartnerRouteRouteImport } from './routes/_authenticated/partner/route'
import { Route as AuthenticatedClientRouteRouteImport } from './routes/_authenticated/client/route'
import { Route as AuthenticatedAdminRouteRouteImport } from './routes/_authenticated/admin/route'
import { Route as AuthenticatedPartnerIndexRouteImport } from './routes/_authenticated/partner/index'
import { Route as AuthenticatedClientIndexRouteImport } from './routes/_authenticated/client/index'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as AuthenticatedPartnerTasksRouteImport } from './routes/_authenticated/partner/tasks'
import { Route as AuthenticatedPartnerFeedbacksRouteImport } from './routes/_authenticated/partner/feedbacks'
import { Route as AuthenticatedPartnerClientsRouteImport } from './routes/_authenticated/partner/clients'
import { Route as AuthenticatedClientStatusRouteImport } from './routes/_authenticated/client/status'
import { Route as AuthenticatedClientDocumentsRouteImport } from './routes/_authenticated/client/documents'
import { Route as AuthenticatedClientConsentsRouteImport } from './routes/_authenticated/client/consents'
import { Route as AuthenticatedAdminTransactionsRouteImport } from './routes/_authenticated/admin/transactions'
import { Route as AuthenticatedAdminTasksRouteImport } from './routes/_authenticated/admin/tasks'
import { Route as AuthenticatedAdminPartnersRouteImport } from './routes/_authenticated/admin/partners'
import { Route as AuthenticatedAdminIntegrationsRouteImport } from './routes/_authenticated/admin/integrations'
import { Route as AuthenticatedAdminContentRouteImport } from './routes/_authenticated/admin/content'
import { Route as AuthenticatedAdminClientsRouteImport } from './routes/_authenticated/admin/clients'
import { Route as AuthenticatedAdminAccessRouteImport } from './routes/_authenticated/admin/access'
import { Route as ApiPublicWebhooksIncomingRouteImport } from './routes/api/public/webhooks/incoming'
import { Route as ApiPublicLeadsSubmitRouteImport } from './routes/api/public/leads/submit'
import { Route as ApiPublicHooksSlaMonitorRouteImport } from './routes/api/public/hooks/sla-monitor'
import { Route as ApiPublicHooksOutboxDispatchRouteImport } from './routes/api/public/hooks/outbox-dispatch'
import { Route as AuthenticatedAdminClientsClientIdRouteImport } from './routes/_authenticated/admin/clients.$clientId'

const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedPartnerRouteRoute =
  AuthenticatedPartnerRouteRouteImport.update({
    id: '/partner',
    path: '/partner',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedClientRouteRoute =
  AuthenticatedClientRouteRouteImport.update({
    id: '/client',
    path: '/client',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminRouteRoute = AuthenticatedAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPartnerIndexRoute =
  AuthenticatedPartnerIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedPartnerRouteRoute,
  } as any)
const AuthenticatedClientIndexRoute =
  AuthenticatedClientIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedClientRouteRoute,
  } as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedPartnerTasksRoute =
  AuthenticatedPartnerTasksRouteImport.update({
    id: '/tasks',
    path: '/tasks',
    getParentRoute: () => AuthenticatedPartnerRouteRoute,
  } as any)
const AuthenticatedPartnerFeedbacksRoute =
  AuthenticatedPartnerFeedbacksRouteImport.update({
    id: '/feedbacks',
    path: '/feedbacks',
    getParentRoute: () => AuthenticatedPartnerRouteRoute,
  } as any)
const AuthenticatedPartnerClientsRoute =
  AuthenticatedPartnerClientsRouteImport.update({
    id: '/clients',
    path: '/clients',
    getParentRoute: () => AuthenticatedPartnerRouteRoute,
  } as any)
const AuthenticatedClientStatusRoute =
  AuthenticatedClientStatusRouteImport.update({
    id: '/status',
    path: '/status',
    getParentRoute: () => AuthenticatedClientRouteRoute,
  } as any)
const AuthenticatedClientDocumentsRoute =
  AuthenticatedClientDocumentsRouteImport.update({
    id: '/documents',
    path: '/documents',
    getParentRoute: () => AuthenticatedClientRouteRoute,
  } as any)
const AuthenticatedClientConsentsRoute =
  AuthenticatedClientConsentsRouteImport.update({
    id: '/consents',
    path: '/consents',
    getParentRoute: () => AuthenticatedClientRouteRoute,
  } as any)
const AuthenticatedAdminTransactionsRoute =
  AuthenticatedAdminTransactionsRouteImport.update({
    id: '/transactions',
    path: '/transactions',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminTasksRoute = AuthenticatedAdminTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminPartnersRoute =
  AuthenticatedAdminPartnersRouteImport.update({
    id: '/partners',
    path: '/partners',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminIntegrationsRoute =
  AuthenticatedAdminIntegrationsRouteImport.update({
    id: '/integrations',
    path: '/integrations',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminContentRoute =
  AuthenticatedAdminContentRouteImport.update({
    id: '/content',
    path: '/content',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminClientsRoute =
  AuthenticatedAdminClientsRouteImport.update({
    id: '/clients',
    path: '/clients',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminAccessRoute =
  AuthenticatedAdminAccessRouteImport.update({
    id: '/access',
    path: '/access',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const ApiPublicWebhooksIncomingRoute =
  ApiPublicWebhooksIncomingRouteImport.update({
    id: '/api/public/webhooks/incoming',
    path: '/api/public/webhooks/incoming',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicLeadsSubmitRoute = ApiPublicLeadsSubmitRouteImport.update({
  id: '/api/public/leads/submit',
  path: '/api/public/leads/submit',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksSlaMonitorRoute =
  ApiPublicHooksSlaMonitorRouteImport.update({
    id: '/api/public/hooks/sla-monitor',
    path: '/api/public/hooks/sla-monitor',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksOutboxDispatchRoute =
  ApiPublicHooksOutboxDispatchRouteImport.update({
    id: '/api/public/hooks/outbox-dispatch',
    path: '/api/public/hooks/outbox-dispatch',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedAdminClientsClientIdRoute =
  AuthenticatedAdminClientsClientIdRouteImport.update({
    id: '/$clientId',
    path: '/$clientId',
    getParentRoute: () => AuthenticatedAdminClientsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/client': typeof AuthenticatedClientRouteRouteWithChildren
  '/partner': typeof AuthenticatedPartnerRouteRouteWithChildren
  '/admin/access': typeof AuthenticatedAdminAccessRoute
  '/admin/clients': typeof AuthenticatedAdminClientsRouteWithChildren
  '/admin/content': typeof AuthenticatedAdminContentRoute
  '/admin/integrations': typeof AuthenticatedAdminIntegrationsRoute
  '/admin/partners': typeof AuthenticatedAdminPartnersRoute
  '/admin/tasks': typeof AuthenticatedAdminTasksRoute
  '/admin/transactions': typeof AuthenticatedAdminTransactionsRoute
  '/client/consents': typeof AuthenticatedClientConsentsRoute
  '/client/documents': typeof AuthenticatedClientDocumentsRoute
  '/client/status': typeof AuthenticatedClientStatusRoute
  '/partner/clients': typeof AuthenticatedPartnerClientsRoute
  '/partner/feedbacks': typeof AuthenticatedPartnerFeedbacksRoute
  '/partner/tasks': typeof AuthenticatedPartnerTasksRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/client/': typeof AuthenticatedClientIndexRoute
  '/partner/': typeof AuthenticatedPartnerIndexRoute
  '/admin/clients/$clientId': typeof AuthenticatedAdminClientsClientIdRoute
  '/api/public/hooks/outbox-dispatch': typeof ApiPublicHooksOutboxDispatchRoute
  '/api/public/hooks/sla-monitor': typeof ApiPublicHooksSlaMonitorRoute
  '/api/public/leads/submit': typeof ApiPublicLeadsSubmitRoute
  '/api/public/webhooks/incoming': typeof ApiPublicWebhooksIncomingRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/admin/access': typeof AuthenticatedAdminAccessRoute
  '/admin/clients': typeof AuthenticatedAdminClientsRouteWithChildren
  '/admin/content': typeof AuthenticatedAdminContentRoute
  '/admin/integrations': typeof AuthenticatedAdminIntegrationsRoute
  '/admin/partners': typeof AuthenticatedAdminPartnersRoute
  '/admin/tasks': typeof AuthenticatedAdminTasksRoute
  '/admin/transactions': typeof AuthenticatedAdminTransactionsRoute
  '/client/consents': typeof AuthenticatedClientConsentsRoute
  '/client/documents': typeof AuthenticatedClientDocumentsRoute
  '/client/status': typeof AuthenticatedClientStatusRoute
  '/partner/clients': typeof AuthenticatedPartnerClientsRoute
  '/partner/feedbacks': typeof AuthenticatedPartnerFeedbacksRoute
  '/partner/tasks': typeof AuthenticatedPartnerTasksRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/client': typeof AuthenticatedClientIndexRoute
  '/partner': typeof AuthenticatedPartnerIndexRoute
  '/admin/clients/$clientId': typeof AuthenticatedAdminClientsClientIdRoute
  '/api/public/hooks/outbox-dispatch': typeof ApiPublicHooksOutboxDispatchRoute
  '/api/public/hooks/sla-monitor': typeof ApiPublicHooksSlaMonitorRoute
  '/api/public/leads/submit': typeof ApiPublicLeadsSubmitRoute
  '/api/public/webhooks/incoming': typeof ApiPublicWebhooksIncomingRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/_authenticated/client': typeof AuthenticatedClientRouteRouteWithChildren
  '/_authenticated/partner': typeof AuthenticatedPartnerRouteRouteWithChildren
  '/_authenticated/admin/access': typeof AuthenticatedAdminAccessRoute
  '/_authenticated/admin/clients': typeof AuthenticatedAdminClientsRouteWithChildren
  '/_authenticated/admin/content': typeof AuthenticatedAdminContentRoute
  '/_authenticated/admin/integrations': typeof AuthenticatedAdminIntegrationsRoute
  '/_authenticated/admin/partners': typeof AuthenticatedAdminPartnersRoute
  '/_authenticated/admin/tasks': typeof AuthenticatedAdminTasksRoute
  '/_authenticated/admin/transactions': typeof AuthenticatedAdminTransactionsRoute
  '/_authenticated/client/consents': typeof AuthenticatedClientConsentsRoute
  '/_authenticated/client/documents': typeof AuthenticatedClientDocumentsRoute
  '/_authenticated/client/status': typeof AuthenticatedClientStatusRoute
  '/_authenticated/partner/clients': typeof AuthenticatedPartnerClientsRoute
  '/_authenticated/partner/feedbacks': typeof AuthenticatedPartnerFeedbacksRoute
  '/_authenticated/partner/tasks': typeof AuthenticatedPartnerTasksRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/client/': typeof AuthenticatedClientIndexRoute
  '/_authenticated/partner/': typeof AuthenticatedPartnerIndexRoute
  '/_authenticated/admin/clients/$clientId': typeof AuthenticatedAdminClientsClientIdRoute
  '/api/public/hooks/outbox-dispatch': typeof ApiPublicHooksOutboxDispatchRoute
  '/api/public/hooks/sla-monitor': typeof ApiPublicHooksSlaMonitorRoute
  '/api/public/leads/submit': typeof ApiPublicLeadsSubmitRoute
  '/api/public/webhooks/incoming': typeof ApiPublicWebhooksIncomingRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/contact'
    | '/admin'
    | '/client'
    | '/partner'
    | '/admin/access'
    | '/admin/clients'
    | '/admin/content'
    | '/admin/integrations'
    | '/admin/partners'
    | '/admin/tasks'
    | '/admin/transactions'
    | '/client/consents'
    | '/client/documents'
    | '/client/status'
    | '/partner/clients'
    | '/partner/feedbacks'
    | '/partner/tasks'
    | '/admin/'
    | '/client/'
    | '/partner/'
    | '/admin/clients/$clientId'
    | '/api/public/hooks/outbox-dispatch'
    | '/api/public/hooks/sla-monitor'
    | '/api/public/leads/submit'
    | '/api/public/webhooks/incoming'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/contact'
    | '/admin/access'
    | '/admin/clients'
    | '/admin/content'
    | '/admin/integrations'
    | '/admin/partners'
    | '/admin/tasks'
    | '/admin/transactions'
    | '/client/consents'
    | '/client/documents'
    | '/client/status'
    | '/partner/clients'
    | '/partner/feedbacks'
    | '/partner/tasks'
    | '/admin'
    | '/client'
    | '/partner'
    | '/admin/clients/$clientId'
    | '/api/public/hooks/outbox-dispatch'
    | '/api/public/hooks/sla-monitor'
    | '/api/public/leads/submit'
    | '/api/public/webhooks/incoming'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/contact'
    | '/_authenticated/admin'
    | '/_authenticated/client'
    | '/_authenticated/partner'
    | '/_authenticated/admin/access'
    | '/_authenticated/admin/clients'
    | '/_authenticated/admin/content'
    | '/_authenticated/admin/integrations'
    | '/_authenticated/admin/partners'
    | '/_authenticated/admin/tasks'
    | '/_authenticated/admin/transactions'
    | '/_authenticated/client/consents'
    | '/_authenticated/client/documents'
    | '/_authenticated/client/status'
    | '/_authenticated/partner/clients'
    | '/_authenticated/partner/feedbacks'
    | '/_authenticated/partner/tasks'
    | '/_authenticated/admin/'
    | '/_authenticated/client/'
    | '/_authenticated/partner/'
    | '/_authenticated/admin/clients/$clientId'
    | '/api/public/hooks/outbox-dispatch'
    | '/api/public/hooks/sla-monitor'
    | '/api/public/leads/submit'
    | '/api/public/webhooks/incoming'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ContactRoute: typeof ContactRoute
  ApiPublicHooksOutboxDispatchRoute: typeof ApiPublicHooksOutboxDispatchRoute
  ApiPublicHooksSlaMonitorRoute: typeof ApiPublicHooksSlaMonitorRoute
  ApiPublicLeadsSubmitRoute: typeof ApiPublicLeadsSubmitRoute
  ApiPublicWebhooksIncomingRoute: typeof ApiPublicWebhooksIncomingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/partner': {
      id: '/_authenticated/partner'
      path: '/partner'
      fullPath: '/partner'
      preLoaderRoute: typeof AuthenticatedPartnerRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/client': {
      id: '/_authenticated/client'
      path: '/client'
      fullPath: '/client'
      preLoaderRoute: typeof AuthenticatedClientRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/partner/': {
      id: '/_authenticated/partner/'
      path: '/'
      fullPath: '/partner/'
      preLoaderRoute: typeof AuthenticatedPartnerIndexRouteImport
      parentRoute: typeof AuthenticatedPartnerRouteRoute
    }
    '/_authenticated/client/': {
      id: '/_authenticated/client/'
      path: '/'
      fullPath: '/client/'
      preLoaderRoute: typeof AuthenticatedClientIndexRouteImport
      parentRoute: typeof AuthenticatedClientRouteRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/partner/tasks': {
      id: '/_authenticated/partner/tasks'
      path: '/tasks'
      fullPath: '/partner/tasks'
      preLoaderRoute: typeof AuthenticatedPartnerTasksRouteImport
      parentRoute: typeof AuthenticatedPartnerRouteRoute
    }
    '/_authenticated/partner/feedbacks': {
      id: '/_authenticated/partner/feedbacks'
      path: '/feedbacks'
      fullPath: '/partner/feedbacks'
      preLoaderRoute: typeof AuthenticatedPartnerFeedbacksRouteImport
      parentRoute: typeof AuthenticatedPartnerRouteRoute
    }
    '/_authenticated/partner/clients': {
      id: '/_authenticated/partner/clients'
      path: '/clients'
      fullPath: '/partner/clients'
      preLoaderRoute: typeof AuthenticatedPartnerClientsRouteImport
      parentRoute: typeof AuthenticatedPartnerRouteRoute
    }
    '/_authenticated/client/status': {
      id: '/_authenticated/client/status'
      path: '/status'
      fullPath: '/client/status'
      preLoaderRoute: typeof AuthenticatedClientStatusRouteImport
      parentRoute: typeof AuthenticatedClientRouteRoute
    }
    '/_authenticated/client/documents': {
      id: '/_authenticated/client/documents'
      path: '/documents'
      fullPath: '/client/documents'
      preLoaderRoute: typeof AuthenticatedClientDocumentsRouteImport
      parentRoute: typeof AuthenticatedClientRouteRoute
    }
    '/_authenticated/client/consents': {
      id: '/_authenticated/client/consents'
      path: '/consents'
      fullPath: '/client/consents'
      preLoaderRoute: typeof AuthenticatedClientConsentsRouteImport
      parentRoute: typeof AuthenticatedClientRouteRoute
    }
    '/_authenticated/admin/transactions': {
      id: '/_authenticated/admin/transactions'
      path: '/transactions'
      fullPath: '/admin/transactions'
      preLoaderRoute: typeof AuthenticatedAdminTransactionsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/tasks': {
      id: '/_authenticated/admin/tasks'
      path: '/tasks'
      fullPath: '/admin/tasks'
      preLoaderRoute: typeof AuthenticatedAdminTasksRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/partners': {
      id: '/_authenticated/admin/partners'
      path: '/partners'
      fullPath: '/admin/partners'
      preLoaderRoute: typeof AuthenticatedAdminPartnersRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/integrations': {
      id: '/_authenticated/admin/integrations'
      path: '/integrations'
      fullPath: '/admin/integrations'
      preLoaderRoute: typeof AuthenticatedAdminIntegrationsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/content': {
      id: '/_authenticated/admin/content'
      path: '/content'
      fullPath: '/admin/content'
      preLoaderRoute: typeof AuthenticatedAdminContentRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/clients': {
      id: '/_authenticated/admin/clients'
      path: '/clients'
      fullPath: '/admin/clients'
      preLoaderRoute: typeof AuthenticatedAdminClientsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/access': {
      id: '/_authenticated/admin/access'
      path: '/access'
      fullPath: '/admin/access'
      preLoaderRoute: typeof AuthenticatedAdminAccessRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/api/public/webhooks/incoming': {
      id: '/api/public/webhooks/incoming'
      path: '/api/public/webhooks/incoming'
      fullPath: '/api/public/webhooks/incoming'
      preLoaderRoute: typeof ApiPublicWebhooksIncomingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/leads/submit': {
      id: '/api/public/leads/submit'
      path: '/api/public/leads/submit'
      fullPath: '/api/public/leads/submit'
      preLoaderRoute: typeof ApiPublicLeadsSubmitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/sla-monitor': {
      id: '/api/public/hooks/sla-monitor'
      path: '/api/public/hooks/sla-monitor'
      fullPath: '/api/public/hooks/sla-monitor'
      preLoaderRoute: typeof ApiPublicHooksSlaMonitorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/outbox-dispatch': {
      id: '/api/public/hooks/outbox-dispatch'
      path: '/api/public/hooks/outbox-dispatch'
      fullPath: '/api/public/hooks/outbox-dispatch'
      preLoaderRoute: typeof ApiPublicHooksOutboxDispatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/clients/$clientId': {
      id: '/_authenticated/admin/clients/$clientId'
      path: '/$clientId'
      fullPath: '/admin/clients/$clientId'
      preLoaderRoute: typeof AuthenticatedAdminClientsClientIdRouteImport
      parentRoute: typeof AuthenticatedAdminClientsRoute
    }
  }
}

interface AuthenticatedAdminClientsRouteChildren {
  AuthenticatedAdminClientsClientIdRoute: typeof AuthenticatedAdminClientsClientIdRoute
}

const AuthenticatedAdminClientsRouteChildren: AuthenticatedAdminClientsRouteChildren =
  {
    AuthenticatedAdminClientsClientIdRoute:
      AuthenticatedAdminClientsClientIdRoute,
  }

const AuthenticatedAdminClientsRouteWithChildren =
  AuthenticatedAdminClientsRoute._addFileChildren(
    AuthenticatedAdminClientsRouteChildren,
  )

interface AuthenticatedAdminRouteRouteChildren {
  AuthenticatedAdminAccessRoute: typeof AuthenticatedAdminAccessRoute
  AuthenticatedAdminClientsRoute: typeof AuthenticatedAdminClientsRouteWithChildren
  AuthenticatedAdminContentRoute: typeof AuthenticatedAdminContentRoute
  AuthenticatedAdminIntegrationsRoute: typeof AuthenticatedAdminIntegrationsRoute
  AuthenticatedAdminPartnersRoute: typeof AuthenticatedAdminPartnersRoute
  AuthenticatedAdminTasksRoute: typeof AuthenticatedAdminTasksRoute
  AuthenticatedAdminTransactionsRoute: typeof AuthenticatedAdminTransactionsRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteRouteChildren: AuthenticatedAdminRouteRouteChildren =
  {
    AuthenticatedAdminAccessRoute: AuthenticatedAdminAccessRoute,
    AuthenticatedAdminClientsRoute: AuthenticatedAdminClientsRouteWithChildren,
    AuthenticatedAdminContentRoute: AuthenticatedAdminContentRoute,
    AuthenticatedAdminIntegrationsRoute: AuthenticatedAdminIntegrationsRoute,
    AuthenticatedAdminPartnersRoute: AuthenticatedAdminPartnersRoute,
    AuthenticatedAdminTasksRoute: AuthenticatedAdminTasksRoute,
    AuthenticatedAdminTransactionsRoute: AuthenticatedAdminTransactionsRoute,
    AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  }

const AuthenticatedAdminRouteRouteWithChildren =
  AuthenticatedAdminRouteRoute._addFileChildren(
    AuthenticatedAdminRouteRouteChildren,
  )

interface AuthenticatedClientRouteRouteChildren {
  AuthenticatedClientConsentsRoute: typeof AuthenticatedClientConsentsRoute
  AuthenticatedClientDocumentsRoute: typeof AuthenticatedClientDocumentsRoute
  AuthenticatedClientStatusRoute: typeof AuthenticatedClientStatusRoute
  AuthenticatedClientIndexRoute: typeof AuthenticatedClientIndexRoute
}

const AuthenticatedClientRouteRouteChildren: AuthenticatedClientRouteRouteChildren =
  {
    AuthenticatedClientConsentsRoute: AuthenticatedClientConsentsRoute,
    AuthenticatedClientDocumentsRoute: AuthenticatedClientDocumentsRoute,
    AuthenticatedClientStatusRoute: AuthenticatedClientStatusRoute,
    AuthenticatedClientIndexRoute: AuthenticatedClientIndexRoute,
  }

const AuthenticatedClientRouteRouteWithChildren =
  AuthenticatedClientRouteRoute._addFileChildren(
    AuthenticatedClientRouteRouteChildren,
  )

interface AuthenticatedPartnerRouteRouteChildren {
  AuthenticatedPartnerClientsRoute: typeof AuthenticatedPartnerClientsRoute
  AuthenticatedPartnerFeedbacksRoute: typeof AuthenticatedPartnerFeedbacksRoute
  AuthenticatedPartnerTasksRoute: typeof AuthenticatedPartnerTasksRoute
  AuthenticatedPartnerIndexRoute: typeof AuthenticatedPartnerIndexRoute
}

const AuthenticatedPartnerRouteRouteChildren: AuthenticatedPartnerRouteRouteChildren =
  {
    AuthenticatedPartnerClientsRoute: AuthenticatedPartnerClientsRoute,
    AuthenticatedPartnerFeedbacksRoute: AuthenticatedPartnerFeedbacksRoute,
    AuthenticatedPartnerTasksRoute: AuthenticatedPartnerTasksRoute,
    AuthenticatedPartnerIndexRoute: AuthenticatedPartnerIndexRoute,
  }

const AuthenticatedPartnerRouteRouteWithChildren =
  AuthenticatedPartnerRouteRoute._addFileChildren(
    AuthenticatedPartnerRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRouteRoute: typeof AuthenticatedAdminRouteRouteWithChildren
  AuthenticatedClientRouteRoute: typeof AuthenticatedClientRouteRouteWithChildren
  AuthenticatedPartnerRouteRoute: typeof AuthenticatedPartnerRouteRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRouteRoute: AuthenticatedAdminRouteRouteWithChildren,
  AuthenticatedClientRouteRoute: AuthenticatedClientRouteRouteWithChildren,
  AuthenticatedPartnerRouteRoute: AuthenticatedPartnerRouteRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ContactRoute: ContactRoute,
  ApiPublicHooksOutboxDispatchRoute: ApiPublicHooksOutboxDispatchRoute,
  ApiPublicHooksSlaMonitorRoute: ApiPublicHooksSlaMonitorRoute,
  ApiPublicLeadsSubmitRoute: ApiPublicLeadsSubmitRoute,
  ApiPublicWebhooksIncomingRoute: ApiPublicWebhooksIncomingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
