name: Deploy
on:
  push:
    branches: [master]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_IP }}
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /var/www/chizukim-transcribe
            /usr/bin/git pull origin master
            npm install
            npm run build
            pm2 restart chizukim-transcribe
            echo "Deploy done!"
