import { createContext, useContext, useState, ReactNode, useCallback, useEffect, useRef } from "react";
import { useApp } from "./AppContext";
import { supabase } from "@/integrations/supabase/client";

export type TransactionCategory = "food" | "housing" | "health" | "car" | "business" | "education" | "entertainment" | "other";

export interface InstallmentDetails {
  totalAmount: number;
  totalMonths: number;
  currentMonth: number;
  monthlyAmount: number;
  startDate: string;
}

export interface Transaction {
  id: string;
  type: "expense" | "income";
  amount: number;
  category: TransactionCategory;
  description: string;
  date: string;
  isRecurring: boolean;
  isInstallment: boolean;
  installmentDetails?: InstallmentDetails;
}

export interface BudgetLimit {
  category: TransactionCategory;
  limit: number;
}

export interface FamilyEvent {
  id: string;
  childName: string;
  childAge: number;
  eventType: "bar_mitzvah" | "bat_mitzvah" | "wedding";
  eventDate: string;
  targetBudget: number;
  savedAmount: number;
}

export type TaskStatus = "pending" | "done" | "snoozed" | "reminded";

export interface SmartTask {
  id: string;
  title: string;
  description: string;
  dueDate: string;
  status: TaskStatus;
  category: "bill" | "birthday" | "school" | "event" | "vendor" | "general" | "rights";
  linkedEventId?: string;
  linkedSupplierId?: string;
  completionNote?: string;
  completedAt?: string;
  autoGenerated?: boolean;
  autoId?: string;
}

export interface TaskHistoryEntry {
  id: string;
  task: SmartTask;
  completionNote: string;
  completedAt: string;
}

export interface Supplier {
  id: string;
  name: string;
  category: string;
  phone: string;
  email: string;
  rating: number;
  linkedEventIds: string[];
  totalPaid: number;
  nextPaymentDate?: string;
  nextPaymentAmount?: number;
  notes: string;
}

export interface ChatMessage {
  id: string;
  role: "user" | "expert";
  content: string;
  timestamp: string;
}

export interface Benefit {
  id: string;
  title: string;
  description: string;
  eligibility: string;
  ctaLabel: string;
  ctaUrl: string;
  category: "housing" | "health" | "education" | "tax" | "family" | "business";
  icon: string;
}

interface FinancialContextType {
  transactions: Transaction[];
  addTransaction: (tx: Omit<Transaction, "id">) => void;
  updateTransaction: (id: string, updates: Partial<Omit<Transaction, "id">>) => void;
  removeTransaction: (id: string) => void;
  budgetLimits: BudgetLimit[];
  setBudgetLimit: (category: TransactionCategory, limit: number) => void;
  familyEvents: FamilyEvent[];
  addFamilyEvent: (event: Omit<FamilyEvent, "id">) => void;
  updateEventSavings: (id: string, amount: number) => void;
  removeFamilyEvent: (id: string) => void;
  getMonthlyExpenses: (year: number, month: number) => Transaction[];
  getMonthlyIncome: (year: number, month: number) => Transaction[];
  getDailyTransactions: (date: string) => Transaction[];
  getTotalInstallmentDebt: () => number;
  getProjectedMonthlyCharges: (monthsAhead: number) => { month: string; amount: number }[];
  getCategorySpending: (year: number, month: number) => Record<TransactionCategory, number>;
  getMonthlySavingsNeeded: (event: FamilyEvent) => number;
  tasks: SmartTask[];
  addTask: (task: Omit<SmartTask, "id">) => void;
  updateTaskStatus: (id: string, status: TaskStatus) => void;
  completeTask: (id: string, completionNote: string) => void;
  removeTask: (id: string) => void;
  taskHistory: TaskHistoryEntry[];
  suppliers: Supplier[];
  addSupplier: (s: Omit<Supplier, "id">) => void;
  removeSupplier: (id: string) => void;
  updateSupplier: (id: string, updates: Partial<Supplier>) => void;
  chatMessages: ChatMessage[];
  addChatMessage: (msg: Omit<ChatMessage, "id">) => void;
  benefits: Benefit[];
  getUpcomingPayments: () => { supplier: Supplier; daysUntil: number }[];
  loading: boolean;
}

// No default budget limits — user sets their own
function createDefaultBudgetLimits(): BudgetLimit[] {
  return [];
}

// ── Supabase row ↔ local type mappers ──

function mapDbTransaction(row: any): Transaction {
  return {
    id: row.id, type: row.type as "expense" | "income", amount: Number(row.amount),
    category: row.category as TransactionCategory, description: row.description || "",
    date: row.date, isRecurring: row.is_recurring ?? false, isInstallment: row.is_installment ?? false,
    installmentDetails: row.installment_details ? row.installment_details as InstallmentDetails : undefined,
  };
}

function mapDbTask(row: any): SmartTask {
  return {
    id: row.id, title: row.title, description: row.description || "",
    dueDate: row.due_date, status: row.status as TaskStatus,
    category: (row.category || "general") as SmartTask["category"],
    completionNote: row.completion_note || undefined, completedAt: row.completed_at || undefined,
    autoGenerated: row.auto_generated ?? false, autoId: row.auto_id || undefined,
  };
}

function mapDbSupplier(row: any): Supplier {
  return {
    id: row.id, name: row.name, category: row.category || "",
    phone: row.phone || "", email: row.email || "", rating: row.rating ?? 5,
    linkedEventIds: [], totalPaid: Number(row.total_paid) || 0,
    nextPaymentDate: row.next_payment_date || undefined,
    nextPaymentAmount: row.next_payment_amount ? Number(row.next_payment_amount) : undefined,
    notes: row.notes || "",
  };
}

const FinancialContext = createContext<FinancialContextType | undefined>(undefined);

export const FinancialProvider = ({ children }: { children: ReactNode }) => {
  const { profile, userId } = useApp();
  const [transactions, setTransactions] = useState<Transaction[]>([]);
  const [budgetLimits, setBudgetLimitsState] = useState<BudgetLimit[]>(createDefaultBudgetLimits);
  const [tasks, setTasks] = useState<SmartTask[]>([]);
  const [taskHistory, setTaskHistory] = useState<TaskHistoryEntry[]>([]);
  const [suppliers, setSuppliers] = useState<Supplier[]>([]);
  const [chatMessages, setChatMessages] = useState<ChatMessage[]>([]);
  const [familyEvents, setFamilyEvents] = useState<FamilyEvent[]>([]);
  const [benefits] = useState<Benefit[]>([]);
  const [loading, setLoading] = useState(true);
  const rightsGenerated = useRef(false);

  // ── Load data ──
  useEffect(() => {
    if (!userId) {
      setTransactions([]);
      setTasks([]);
      setTaskHistory([]);
      setSuppliers([]);
      setChatMessages([]);
      setFamilyEvents([]);
      setBudgetLimitsState(createDefaultBudgetLimits());
      setLoading(false);
      return;
    }

    // Safety timeout — never stay loading more than 8 seconds
    const timeout = setTimeout(() => setLoading(false), 8000);

    rightsGenerated.current = false;
    setLoading(true);

    // ═══ SUPABASE MODE ═══
    const load = async () => {
      const [txRes, taskRes, histRes, suppRes, chatRes, budgetRes] = await Promise.all([
        supabase.from("transactions").select("*").eq("user_id", userId).order("date", { ascending: false }),
        supabase.from("tasks").select("*").eq("user_id", userId).order("due_date"),
        supabase.from("task_history").select("*").eq("user_id", userId).order("completed_at", { ascending: false }),
        supabase.from("suppliers").select("*").eq("user_id", userId),
        supabase.from("chat_messages").select("*").eq("user_id", userId).order("created_at"),
        supabase.from("budget_limits").select("*").eq("user_id", userId),
      ]);

      setTransactions((txRes.data || []).map(mapDbTransaction));
      setTasks((taskRes.data || []).map(mapDbTask));
      setTaskHistory((histRes.data || []).map((r: any) => ({
        id: r.id,
        task: { id: r.id, title: r.task_title, description: r.task_description || "", dueDate: "", status: "done" as TaskStatus, category: (r.task_category || "general") as SmartTask["category"], autoGenerated: r.auto_generated },
        completionNote: r.completion_note,
        completedAt: r.completed_at,
      })));
      setSuppliers((suppRes.data || []).map(mapDbSupplier));

      const msgs = (chatRes.data || []).map((r: any) => ({
        id: r.id, role: r.role as "user" | "expert", content: r.content, timestamp: r.created_at,
      }));
      setChatMessages(msgs.length > 0 ? msgs : [
        { id: "welcome", role: "expert" as const, content: "שלום! אני היועץ הפיננסי שלך. איך אוכל לעזור לך היום?", timestamp: new Date().toISOString() },
      ]);

      setBudgetLimitsState(
        budgetRes.data && budgetRes.data.length > 0
          ? budgetRes.data.map((r: any) => ({ category: r.category as TransactionCategory, limit: Number(r.amount) }))
          : createDefaultBudgetLimits()
      );

      setLoading(false);
    };
    load();
    return () => clearTimeout(timeout);
  }, [userId]);

  // ── Realtime subscriptions (Supabase only) ──
  useEffect(() => {
    if (!userId) return;

    const txChannel = supabase.channel(`tx-${userId}`)
      .on('postgres_changes', { event: '*', schema: 'public', table: 'transactions', filter: `user_id=eq.${userId}` }, (payload) => {
        if (payload.eventType === 'INSERT') setTransactions(prev => [mapDbTransaction(payload.new), ...prev]);
        else if (payload.eventType === 'UPDATE') setTransactions(prev => prev.map(t => t.id === payload.new.id ? mapDbTransaction(payload.new) : t));
        else if (payload.eventType === 'DELETE') setTransactions(prev => prev.filter(t => t.id !== payload.old.id));
      })
      .subscribe();

    const taskChannel = supabase.channel(`tasks-${userId}`)
      .on('postgres_changes', { event: '*', schema: 'public', table: 'tasks', filter: `user_id=eq.${userId}` }, (payload) => {
        if (payload.eventType === 'INSERT') setTasks(prev => [...prev, mapDbTask(payload.new)]);
        else if (payload.eventType === 'UPDATE') setTasks(prev => prev.map(t => t.id === payload.new.id ? mapDbTask(payload.new) : t));
        else if (payload.eventType === 'DELETE') setTasks(prev => prev.filter(t => t.id !== payload.old.id));
      })
      .subscribe();

    const suppChannel = supabase.channel(`supp-${userId}`)
      .on('postgres_changes', { event: '*', schema: 'public', table: 'suppliers', filter: `user_id=eq.${userId}` }, (payload) => {
        if (payload.eventType === 'INSERT') setSuppliers(prev => [...prev, mapDbSupplier(payload.new)]);
        else if (payload.eventType === 'UPDATE') setSuppliers(prev => prev.map(s => s.id === payload.new.id ? mapDbSupplier(payload.new) : s));
        else if (payload.eventType === 'DELETE') setSuppliers(prev => prev.filter(s => s.id !== payload.old.id));
      })
      .subscribe();

    return () => {
      supabase.removeChannel(txChannel);
      supabase.removeChannel(taskChannel);
      supabase.removeChannel(suppChannel);
    };
  }, [userId]);

  // ── Generate family events from profile ──
  useEffect(() => {
    if (!profile.profileComplete) { setFamilyEvents([]); return; }
    const events: FamilyEvent[] = [];
    profile.childrenAges.forEach((age, idx) => {
      const childName = profile.childrenNames?.[idx] || `ילד ${idx + 1}`;
      if (age < 13) {
        const yearsTo = 13 - age;
        const eventDate = new Date();
        eventDate.setFullYear(eventDate.getFullYear() + yearsTo);
        events.push({ id: `bm-${idx}`, childName, childAge: age, eventType: "bar_mitzvah", eventDate: eventDate.toISOString().split("T")[0], targetBudget: 60000, savedAmount: 0 });
      }
    });
    setFamilyEvents(events);
  }, [profile]);

  // ── Auto-generate rights-based tasks ──
  useEffect(() => {
    if (!userId || !profile.profileComplete || rightsGenerated.current) return;
    rightsGenerated.current = true;

    const existingAutoIds = new Set(tasks.filter(t => t.autoGenerated).map(t => t.autoId || t.id));
    const historyAutoIds = new Set(taskHistory.filter(h => h.task.autoGenerated).map(h => h.task.autoId || h.id));
    const allHandled = new Set([...existingAutoIds, ...historyAutoIds]);

    const newTasks: Array<{ auto_id: string; title: string; description: string; category: string }> = [];

    const maybeAdd = (autoId: string, title: string, desc: string, cat = "rights") => {
      if (!allHandled.has(autoId)) newTasks.push({ auto_id: autoId, title, description: desc, category: cat });
    };

    // Israeli Rights Engine
    if ((profile.sector === "יהודי חרדי" || profile.sector === "יהודי דתי") && profile.childrenCount > 3)
      maybeAdd("auto-arnona-large-family", "בדיקת הנחת ארנונה למשפחות ברוכות ילדים", `מגזר ${profile.sector} עם ${profile.childrenCount} ילדים — בדוק זכאות להנחה בארנונה עד 90%`);
    if (profile.monthlyIncome > 0 && profile.monthlyIncome < 7500)
      maybeAdd("auto-work-grant", "בדיקת זכאות למענק עבודה (מס הכנסה שלילי)", `הכנסתך ₪${profile.monthlyIncome.toLocaleString()} — ייתכן שאתה זכאי למענק עבודה שנתי`);
    if (profile.residentialStatus === "renter" && profile.monthlyIncome > 0 && profile.monthlyIncome < 12000)
      maybeAdd("auto-rent-assist", "סיוע בשכר דירה ממשרד השיכון", `שוכר/ת עם הכנסה ₪${profile.monthlyIncome.toLocaleString()} — בדוק זכאות לסיוע בשכר דירה`);
    if ((profile.healthFund === "מכבי" || profile.healthFund === "כללית") && profile.childrenAges.some(a => a <= 18))
      maybeAdd("auto-health-dental", "מימוש סל טיפולי שיניים מסובסדים לילדים", `חבר/ת ${profile.healthFund} — ילדים עד 18 זכאים לטיפולי שיניים מסובסדים`);
    profile.childrenAges.forEach((age, i) => {
      if (age === 12 && profile.monthlyIncome < 7500) {
        const name = profile.childrenNames[i] || `ילד ${i + 1}`;
        maybeAdd(`auto-barmitzvah-${i}`, `בדוק זכאות למענק בר/בת מצווה — ${name}`, `${name} בגיל 12, הכנסה נמוכה — פנה לרשות המקומית`);
      }
    });
    if (profile.residentialStatus === "renter" && profile.childrenCount >= 3)
      maybeAdd("auto-rent-large-family", "סיוע בשכר דירה למשפחות מרובות ילדים", `שוכר/ת עם ${profile.childrenCount} ילדים — בדוק זכאות מורחבת`);
    if (profile.childrenCount > 0)
      maybeAdd("auto-tax-credits", "וודא שנקודות זיכוי מס מעודכנות", `${profile.childrenCount} ילדים — ודא שנקודות הזיכוי מחושבות נכון`);
    if (profile.childrenAges.some(a => a >= 3 && a <= 5))
      maybeAdd("auto-daycare-subsidy", "בדוק זכאות לסבסוד צהרון/מעון", `ילדים בגיל 3-5 — הורים עובדים זכאים לסבסוד של עד 50%`);
    const totalDebt = (profile.loans || []).reduce((s: number, l: any) => s + (l.totalAmount || 0), 0) + profile.creditCardDebt;
    if (totalDebt > profile.monthlyIncome * 6 && profile.monthlyIncome > 0)
      maybeAdd("auto-debt-counseling", "שקול ייעוץ חובות", `סך חובות ₪${totalDebt.toLocaleString()} — שקול לפנות לייעוץ כלכלי`);
    if ((profile.familyStatus === "גרוש/ה" || profile.familyStatus === "אלמן/ה") && profile.childrenCount > 0)
      maybeAdd("auto-single-parent", "זכויות הורה יחיד/נית", `הורה יחיד/נית עם ${profile.childrenCount} ילדים — בדוק זכאות`);

    if (newTasks.length > 0) {
      const dueDate = new Date(Date.now() + 30 * 86400000).toISOString().split("T")[0];

      const inserts = newTasks.map(t => ({
        user_id: userId, title: t.title, description: t.description,
        category: t.category, due_date: dueDate, status: "pending",
        auto_generated: true, auto_id: t.auto_id,
      }));
      supabase.from("tasks").insert(inserts).then(() => {});
    }

    // Check condition rules
    supabase.from("condition_rules").select("*").then(({ data: rules }) => {
      if (!rules || rules.length === 0) return;
      const ruleInserts: any[] = [];
      rules.forEach((rule: any) => {
        const taskId = `rule-${rule.id}`;
        if (allHandled.has(taskId) || tasks.some(t => t.autoId === taskId)) return;
        let fieldValue = 0;
        if (rule.field === "monthlyIncome") fieldValue = profile.monthlyIncome;
        else if (rule.field === "childrenCount") fieldValue = profile.childrenCount;
        else if (rule.field === "creditCardDebt") fieldValue = profile.creditCardDebt;
        let triggered = false;
        if (rule.operator === "lt" && fieldValue < rule.value) triggered = true;
        if (rule.operator === "gt" && fieldValue > rule.value) triggered = true;
        if (rule.operator === "eq" && fieldValue === rule.value) triggered = true;
        if (rule.operator === "between" && fieldValue >= rule.value && fieldValue <= (rule.value_to || 0)) triggered = true;
        if (triggered) {
          ruleInserts.push({
            user_id: userId, title: rule.alert_title, description: rule.alert_message,
            category: "rights", due_date: new Date(Date.now() + 14 * 86400000).toISOString().split("T")[0],
            status: "pending", auto_generated: true, auto_id: taskId,
          });
        }
      });
      if (ruleInserts.length > 0) supabase.from("tasks").insert(ruleInserts).then(() => {});
    });
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [userId, profile.profileComplete, loading]);

  // ── CRUD operations ──

  const addTransaction = useCallback(async (tx: Omit<Transaction, "id">) => {
    if (!userId) return;
    await supabase.from("transactions").insert({
      user_id: userId, type: tx.type, amount: tx.amount, category: tx.category,
      description: tx.description, date: tx.date, is_recurring: tx.isRecurring,
      is_installment: tx.isInstallment,
      installment_details: tx.installmentDetails ? tx.installmentDetails as any : null,
    });
  }, [userId]);

  const updateTransaction = useCallback(async (id: string, updates: Partial<Omit<Transaction, "id">>) => {
    const dbUpdates: any = {};
    if (updates.type !== undefined) dbUpdates.type = updates.type;
    if (updates.amount !== undefined) dbUpdates.amount = updates.amount;
    if (updates.category !== undefined) dbUpdates.category = updates.category;
    if (updates.description !== undefined) dbUpdates.description = updates.description;
    if (updates.date !== undefined) dbUpdates.date = updates.date;
    if (updates.isRecurring !== undefined) dbUpdates.is_recurring = updates.isRecurring;
    if (updates.isInstallment !== undefined) dbUpdates.is_installment = updates.isInstallment;
    if (updates.installmentDetails !== undefined) dbUpdates.installment_details = updates.installmentDetails;
    await supabase.from("transactions").update(dbUpdates).eq("id", id);
  }, []);

  const removeTransaction = useCallback(async (id: string) => {
    await supabase.from("transactions").delete().eq("id", id);
  }, []);

  const setBudgetLimit = useCallback(async (category: TransactionCategory, limit: number) => {
    if (!userId) return;
    setBudgetLimitsState(prev => prev.map(b => b.category === category ? { ...b, limit } : b));
    const { data } = await supabase.from("budget_limits").select("id").eq("user_id", userId).eq("category", category).single();
    if (data) {
      await supabase.from("budget_limits").update({ amount: limit }).eq("id", data.id);
    } else {
      await supabase.from("budget_limits").insert({ user_id: userId, category, amount: limit });
    }
  }, [userId]);

  const addFamilyEvent = useCallback((event: Omit<FamilyEvent, "id">) => {
    setFamilyEvents(prev => [...prev, { ...event, id: crypto.randomUUID() }]);
  }, []);

  const updateEventSavings = useCallback((id: string, amount: number) => {
    setFamilyEvents(prev => prev.map(e => e.id === id ? { ...e, savedAmount: e.savedAmount + amount } : e));
  }, []);

  const removeFamilyEvent = useCallback((id: string) => {
    setFamilyEvents(prev => prev.filter(e => e.id !== id));
  }, []);

  const addTask = useCallback(async (task: Omit<SmartTask, "id">) => {
    if (!userId) return;
    await supabase.from("tasks").insert({
      user_id: userId, title: task.title, description: task.description,
      due_date: task.dueDate, status: task.status, category: task.category,
      auto_generated: task.autoGenerated || false, auto_id: task.autoId || null,
    });
  }, [userId]);

  const updateTaskStatus = useCallback(async (id: string, status: TaskStatus) => {
    await supabase.from("tasks").update({ status }).eq("id", id);
  }, []);

  const completeTask = useCallback(async (id: string, completionNote: string) => {
    if (!userId) return;
    const task = tasks.find(t => t.id === id);
    if (!task) return;
    const completedAt = new Date().toISOString();

    await Promise.all([
      supabase.from("tasks").delete().eq("id", id),
      supabase.from("task_history").insert({
        user_id: userId, task_title: task.title, task_description: task.description,
        task_category: task.category, completion_note: completionNote,
        completed_at: completedAt, auto_generated: task.autoGenerated || false,
        auto_id: task.autoId || null,
      }),
    ]);
    setTasks(prev => prev.filter(t => t.id !== id));
    setTaskHistory(prev => [{
      id: crypto.randomUUID(),
      task: { ...task, status: "done", completionNote, completedAt },
      completionNote, completedAt,
    }, ...prev]);
  }, [userId, tasks]);

  const removeTask = useCallback(async (id: string) => {
    await supabase.from("tasks").delete().eq("id", id);
  }, []);

  const addSupplier = useCallback(async (s: Omit<Supplier, "id">) => {
    if (!userId) return;
    await supabase.from("suppliers").insert({
      user_id: userId, name: s.name, category: s.category, phone: s.phone,
      email: s.email, rating: s.rating, total_paid: s.totalPaid,
      next_payment_date: s.nextPaymentDate || null,
      next_payment_amount: s.nextPaymentAmount || null, notes: s.notes,
    });
  }, [userId]);

  const removeSupplier = useCallback(async (id: string) => {
    await supabase.from("suppliers").delete().eq("id", id);
  }, []);

  const updateSupplier = useCallback(async (id: string, updates: Partial<Supplier>) => {
    const dbUpdates: any = {};
    if (updates.name !== undefined) dbUpdates.name = updates.name;
    if (updates.category !== undefined) dbUpdates.category = updates.category;
    if (updates.phone !== undefined) dbUpdates.phone = updates.phone;
    if (updates.email !== undefined) dbUpdates.email = updates.email;
    if (updates.rating !== undefined) dbUpdates.rating = updates.rating;
    if (updates.totalPaid !== undefined) dbUpdates.total_paid = updates.totalPaid;
    if (updates.nextPaymentDate !== undefined) dbUpdates.next_payment_date = updates.nextPaymentDate;
    if (updates.nextPaymentAmount !== undefined) dbUpdates.next_payment_amount = updates.nextPaymentAmount;
    if (updates.notes !== undefined) dbUpdates.notes = updates.notes;
    await supabase.from("suppliers").update(dbUpdates).eq("id", id);
  }, []);

  const addChatMessage = useCallback(async (msg: Omit<ChatMessage, "id">) => {
    if (!userId) return;
    const newMsg = { ...msg, id: crypto.randomUUID() };
    setChatMessages(prev => [...prev, newMsg]);
    await supabase.from("chat_messages").insert({
      user_id: userId, role: msg.role, content: msg.content,
    });
  }, [userId]);

  // ── Computed helpers ──

  const getUpcomingPayments = useCallback(() => {
    const today = new Date();
    return suppliers
      .filter(s => s.nextPaymentDate && s.nextPaymentAmount)
      .map(s => {
        const payDate = new Date(s.nextPaymentDate!);
        const daysUntil = Math.ceil((payDate.getTime() - today.getTime()) / (1000 * 60 * 60 * 24));
        return { supplier: s, daysUntil };
      })
      .filter(p => p.daysUntil >= 0 && p.daysUntil <= 60)
      .sort((a, b) => a.daysUntil - b.daysUntil);
  }, [suppliers]);

  const getMonthlyExpenses = useCallback((year: number, month: number) => {
    return transactions.filter(t => { const d = new Date(t.date); return t.type === "expense" && d.getFullYear() === year && d.getMonth() === month; });
  }, [transactions]);

  const getMonthlyIncome = useCallback((year: number, month: number) => {
    return transactions.filter(t => { const d = new Date(t.date); return t.type === "income" && d.getFullYear() === year && d.getMonth() === month; });
  }, [transactions]);

  const getDailyTransactions = useCallback((date: string) => transactions.filter(t => t.date === date), [transactions]);

  const getTotalInstallmentDebt = useCallback(() => {
    return transactions.filter(t => t.isInstallment && t.installmentDetails)
      .reduce((sum, t) => { const remaining = t.installmentDetails!.totalMonths - t.installmentDetails!.currentMonth; return sum + remaining * t.installmentDetails!.monthlyAmount; }, 0);
  }, [transactions]);

  const getProjectedMonthlyCharges = useCallback((monthsAhead: number) => {
    const result: { month: string; amount: number }[] = [];
    const recurringExpenses = transactions.filter(t => t.type === "expense" && (t.isRecurring || t.isInstallment));
    for (let i = 0; i < monthsAhead; i++) {
      const futureDate = new Date(); futureDate.setMonth(futureDate.getMonth() + i);
      const monthLabel = futureDate.toLocaleDateString("he-IL", { month: "short", year: "2-digit" });
      let total = 0;
      recurringExpenses.forEach(t => {
        if (t.isInstallment && t.installmentDetails) {
          if (i < t.installmentDetails.totalMonths - t.installmentDetails.currentMonth) total += t.installmentDetails.monthlyAmount;
        } else if (t.isRecurring) total += t.amount;
      });
      suppliers.forEach(s => {
        if (s.nextPaymentDate && s.nextPaymentAmount) {
          const payDate = new Date(s.nextPaymentDate);
          if (payDate.getMonth() === futureDate.getMonth() && payDate.getFullYear() === futureDate.getFullYear()) total += s.nextPaymentAmount;
        }
      });
      result.push({ month: monthLabel, amount: total });
    }
    return result;
  }, [transactions, suppliers]);

  const getCategorySpending = useCallback((year: number, month: number) => {
    const spending: Record<TransactionCategory, number> = { food: 0, housing: 0, health: 0, car: 0, business: 0, education: 0, entertainment: 0, other: 0 };
    getMonthlyExpenses(year, month).forEach(t => { spending[t.category] += t.amount; });
    return spending;
  }, [getMonthlyExpenses]);

  const getMonthlySavingsNeeded = useCallback((event: FamilyEvent) => {
    const remaining = event.targetBudget - event.savedAmount;
    if (remaining <= 0) return 0;
    const eventDate = new Date(event.eventDate);
    const nowDate = new Date();
    const monthsLeft = Math.max(1, (eventDate.getFullYear() - nowDate.getFullYear()) * 12 + (eventDate.getMonth() - nowDate.getMonth()));
    return Math.ceil(remaining / monthsLeft);
  }, []);

  return (
    <FinancialContext.Provider
      value={{
        transactions, addTransaction, updateTransaction, removeTransaction,
        budgetLimits, setBudgetLimit,
        familyEvents, addFamilyEvent, updateEventSavings, removeFamilyEvent,
        getMonthlyExpenses, getMonthlyIncome, getDailyTransactions,
        getTotalInstallmentDebt, getProjectedMonthlyCharges,
        getCategorySpending, getMonthlySavingsNeeded,
        tasks, addTask, updateTaskStatus, completeTask, removeTask, taskHistory,
        suppliers, addSupplier, removeSupplier, updateSupplier,
        chatMessages, addChatMessage,
        benefits, getUpcomingPayments, loading,
      }}
    >
      {children}
    </FinancialContext.Provider>
  );
};

export const useFinancial = () => {
  const ctx = useContext(FinancialContext);
  if (!ctx) throw new Error("useFinancial must be used within FinancialProvider");
  return ctx;
};
