import { useState, useEffect, useCallback } from "react";
import { motion, AnimatePresence } from "framer-motion";
import { Shield, Search, CheckCircle2, Clock, AlertCircle, Sparkles, ArrowRight, Bell, ChevronDown, ChevronUp, X, CalendarDays, HandHelping, UserCheck } from "lucide-react";
import { useApp } from "@/contexts/AppContext";
import { useFinancial } from "@/contexts/FinancialContext";
import { supabase } from "@/integrations/supabase/client";
import { toast } from "sonner";
import RightsInquiryForm from "@/components/RightsInquiryForm";
import { mainCategories, type MainCategory, type RightTopic } from "@/data/rightsData";
import { Input } from "@/components/ui/input";

const containerVariants = {
  hidden: { opacity: 0 },
  show: { opacity: 1, transition: { staggerChildren: 0.06 } },
};
const itemVariants = {
  hidden: { opacity: 0, y: 12 },
  show: { opacity: 1, y: 0, transition: { duration: 0.35 } },
};

type BenefitInterest = "not_started" | "interested" | "not_relevant" | "later" | "diy" | "help_requested" | "claimed";

const interestConfig: Record<BenefitInterest, { label: string; color: string; icon: typeof CheckCircle2 }> = {
  not_started: { label: "חדש", color: "bg-muted text-muted-foreground", icon: Sparkles },
  interested: { label: "מעניין אותי", color: "bg-accent/10 text-accent", icon: AlertCircle },
  not_relevant: { label: "לא רלוונטי", color: "bg-secondary text-muted-foreground", icon: X },
  later: { label: "מאוחר יותר", color: "bg-amber-500/10 text-amber-400", icon: Clock },
  diy: { label: "אעשה לבד", color: "bg-blue-500/10 text-blue-400", icon: UserCheck },
  help_requested: { label: "מבקש עזרה", color: "bg-emerald-500/10 text-emerald-400", icon: HandHelping },
  claimed: { label: "מומשה", color: "bg-emerald-500/10 text-emerald-400", icon: CheckCircle2 },
};

export default function BenefitsPage() {
  const { userId } = useApp();
  const { addTask } = useFinancial();
  const [search, setSearch] = useState("");
  const [expandedCategory, setExpandedCategory] = useState<string | null>(null);
  const [expandedTopic, setExpandedTopic] = useState<string | null>(null);
  const [savedStatuses, setSavedStatuses] = useState<Record<string, BenefitInterest>>({});
  const [loadingStatuses, setLoadingStatuses] = useState(true);
  const [reminderDate, setReminderDate] = useState<Record<string, string>>({});
  const [laterMonth, setLaterMonth] = useState<Record<string, string>>({});

  useEffect(() => {
    if (!userId) { setLoadingStatuses(false); return; }
    supabase.from("benefit_statuses").select("benefit_key, status").eq("user_id", userId)
      .then(({ data }) => {
        if (data) {
          const map: Record<string, BenefitInterest> = {};
          data.forEach((r: any) => { map[r.benefit_key] = r.status as BenefitInterest; });
          setSavedStatuses(map);
        }
        setLoadingStatuses(false);
      });
  }, [userId]);

  const updateStatus = useCallback(async (topicId: string, status: BenefitInterest) => {
    if (!userId) return;
    setSavedStatuses(prev => ({ ...prev, [topicId]: status }));
    await supabase.from("benefit_statuses").upsert(
      { user_id: userId, benefit_key: topicId, status, updated_at: new Date().toISOString() },
      { onConflict: "user_id,benefit_key" }
    );
  }, [userId]);

  const handleInterested = (topic: RightTopic) => {
    setExpandedTopic(topic.id);
    updateStatus(topic.id, "interested");
  };

  const handleNotRelevant = (topicId: string) => {
    updateStatus(topicId, "not_relevant");
    toast.success("סומן כלא רלוונטי — לא יופיע שוב בשנה הקרובה");
  };

  const handleDIY = async (topic: RightTopic) => {
    const date = reminderDate[topic.id] || new Date(Date.now() + 7 * 86400000).toISOString().split("T")[0];
    updateStatus(topic.id, "diy");
    await addTask({
      title: `לבצע: ${topic.label}`,
      description: `${topic.desc}\n\nשאלות לבדיקה:\n${topic.questions.map((q, i) => `${i + 1}. ${q}`).join("\n")}`,
      dueDate: date,
      status: "pending",
      category: "rights",
      autoGenerated: false,
    });
    toast.success(`תזכורת נקבעה ל-${new Date(date).toLocaleDateString("he-IL")}`);
  };

  const handleHelpRequest = async (topic: RightTopic) => {
    if (!userId) return;
    updateStatus(topic.id, "help_requested");
    await supabase.from("leads").insert({
      name: "",
      email: "",
      phone: "",
      source: "rights_help",
      message: `בקשת עזרה בנושא: ${topic.label} — ${topic.desc}`,
    });
    toast.success("הבקשה נשלחה! נחזור אליך בהקדם");
  };

  const handleLater = async (topic: RightTopic) => {
    const monthValue = laterMonth[topic.id];
    let date: string;
    if (monthValue) {
      date = monthValue;
    } else {
      const d = new Date();
      d.setMonth(d.getMonth() + 1);
      date = d.toISOString().split("T")[0];
    }
    updateStatus(topic.id, "later");
    await addTask({
      title: `תזכורת: ${topic.label}`,
      description: topic.desc,
      dueDate: date,
      status: "pending",
      category: "rights",
      autoGenerated: true,
    });
    toast.success(`תזכורת נקבעה ל-${new Date(date).toLocaleDateString("he-IL")}`);
  };

  const now = new Date();
  const oneYearAgo = new Date(now.getFullYear() - 1, now.getMonth(), now.getDate());

  const filteredCategories = search
    ? mainCategories.map(cat => ({
        ...cat,
        topics: cat.topics.filter(t =>
          t.label.includes(search) || t.desc.includes(search) || t.questions.some(q => q.includes(search))
        ),
      })).filter(cat => cat.topics.length > 0)
    : mainCategories;

  const totalTopics = mainCategories.reduce((s, c) => s + c.topics.length, 0);
  const interestedCount = Object.values(savedStatuses).filter(s => s === "interested" || s === "diy" || s === "help_requested").length;
  const claimedCount = Object.values(savedStatuses).filter(s => s === "claimed").length;

  if (loadingStatuses) {
    return (
      <div className="p-8 max-w-5xl mx-auto space-y-6">
        {[...Array(3)].map((_, i) => <div key={i} className="h-32 rounded-3xl bg-secondary/40 animate-pulse" />)}
      </div>
    );
  }

  return (
    <motion.div variants={containerVariants} initial="hidden" animate="show" className="p-8 md:p-12 max-w-5xl mx-auto space-y-8">
      <motion.div variants={itemVariants}>
        <h1 className="text-2xl md:text-3xl font-extrabold text-foreground tracking-tight">
          <Shield className="w-7 h-7 inline-block me-2 gold-text" />
          זכויות והטבות
        </h1>
        <p className="text-sm text-muted-foreground">{totalTopics} נושאים · סמן מה מעניין אותך ונעזור לך לממש</p>
      </motion.div>

      {/* Summary */}
      <motion.div variants={itemVariants} className="grid grid-cols-3 gap-4">
        <div className="bento-card text-center">
          <p className="text-2xl font-extrabold text-foreground">{totalTopics}</p>
          <p className="text-[10px] text-muted-foreground mt-1">נושאים במאגר</p>
        </div>
        <div className="bento-card text-center">
          <p className="text-2xl font-extrabold text-accent">{interestedCount}</p>
          <p className="text-[10px] text-muted-foreground mt-1">בטיפול</p>
        </div>
        <div className="bento-card text-center">
          <p className="text-2xl font-extrabold text-emerald-400">{claimedCount}</p>
          <p className="text-[10px] text-muted-foreground mt-1">מומשו</p>
        </div>
      </motion.div>

      {/* Search */}
      <motion.div variants={itemVariants} className="relative">
        <Search className="absolute start-4 top-1/2 -translate-y-1/2 w-4 h-4 text-muted-foreground" />
        <input type="text" value={search} onChange={(e) => setSearch(e.target.value)}
          placeholder="חפש זכות, הטבה או נושא..."
          className="w-full ps-11 pe-4 py-3 rounded-2xl bg-secondary border border-border/30 text-foreground text-sm focus:outline-none focus:ring-2 focus:ring-ring" />
      </motion.div>

      {/* Categories accordion */}
      <div className="space-y-3">
        {filteredCategories.map((cat) => {
          const CatIcon = cat.icon;
          const isExpanded = expandedCategory === cat.id;
          const catStatuses = cat.topics.map(t => savedStatuses[t.id]).filter(Boolean);
          const catClaimed = catStatuses.filter(s => s === "claimed").length;

          return (
            <motion.div key={cat.id} variants={itemVariants} className="bento-card overflow-hidden">
              <button
                onClick={() => setExpandedCategory(isExpanded ? null : cat.id)}
                className="w-full flex items-center gap-4 text-start"
              >
                <div className={`p-3 rounded-2xl bg-gradient-to-br ${cat.gradient} text-white shrink-0`}>
                  <CatIcon className="w-5 h-5" />
                </div>
                <div className="flex-1 min-w-0">
                  <h3 className="text-sm font-bold text-foreground">{cat.label}</h3>
                  <p className="text-[10px] text-muted-foreground">{cat.desc} · {cat.topics.length} נושאים</p>
                </div>
                <div className="flex items-center gap-2 shrink-0">
                  {catClaimed > 0 && (
                    <span className="text-[9px] px-2 py-0.5 rounded-full bg-emerald-500/10 text-emerald-400 font-bold">{catClaimed} מומשו</span>
                  )}
                  {isExpanded ? <ChevronUp className="w-4 h-4 text-muted-foreground" /> : <ChevronDown className="w-4 h-4 text-muted-foreground" />}
                </div>
              </button>

              <AnimatePresence>
                {isExpanded && (
                  <motion.div
                    initial={{ height: 0, opacity: 0 }}
                    animate={{ height: "auto", opacity: 1 }}
                    exit={{ height: 0, opacity: 0 }}
                    className="mt-4 space-y-2 border-t border-border/20 pt-4"
                  >
                    {cat.topics.map((topic) => {
                      const status = savedStatuses[topic.id] || "not_started";
                      // Hide "not_relevant" topics (they were marked within the past year)
                      if (status === "not_relevant") return null;
                      
                      const statusCfg = interestConfig[status];
                      const StatusIcon = statusCfg.icon;
                      const isTopicExpanded = expandedTopic === topic.id;

                      return (
                        <div key={topic.id} className="rounded-2xl border border-border/30 bg-secondary/20 p-4 space-y-3">
                          <div className="flex items-start gap-3">
                            <div className="flex-1">
                              <div className="flex items-center gap-2 mb-1 flex-wrap">
                                <span className={`px-2 py-0.5 rounded-full text-[9px] font-bold flex items-center gap-1 ${statusCfg.color}`}>
                                  <StatusIcon className="w-3 h-3" />{statusCfg.label}
                                </span>
                              </div>
                              <h4 className="text-sm font-bold text-foreground">{topic.label}</h4>
                              <p className="text-xs text-muted-foreground mt-1">{topic.desc}</p>
                            </div>
                          </div>

                          {/* Initial action buttons — for new/unseen topics */}
                          {status === "not_started" && (
                            <div className="flex gap-2 flex-wrap">
                              <button onClick={() => handleInterested(topic)}
                                className="btn-clay-gold flex items-center gap-1.5 py-2 px-3 text-[10px]">
                                <Sparkles className="w-3 h-3" />מעניין אותי
                              </button>
                              <button onClick={() => handleNotRelevant(topic.id)}
                                className="btn-clay-ghost flex items-center gap-1.5 py-2 px-3 text-[10px]">
                                <X className="w-3 h-3" />לא רלוונטי
                              </button>
                              <button onClick={() => {
                                setExpandedTopic(topic.id);
                                updateStatus(topic.id, "later");
                              }}
                                className="btn-clay-ghost flex items-center gap-1.5 py-2 px-3 text-[10px] text-amber-400">
                                <Clock className="w-3 h-3" />אולי מאוחר יותר
                              </button>
                            </div>
                          )}

                          {/* Expanded view when interested */}
                          {(status === "interested" || isTopicExpanded) && status !== "not_started" && status !== "claimed" && (
                            <div className="space-y-3 pt-2 border-t border-border/20">
                              {/* Questions */}
                              <div className="space-y-2">
                                <p className="text-[11px] font-bold text-foreground">שאלות לבדיקת זכאות:</p>
                                {topic.questions.map((q, i) => (
                                  <div key={i} className="flex items-start gap-2">
                                    <span className="w-5 h-5 rounded-full bg-accent/10 gold-text text-[10px] font-bold flex items-center justify-center shrink-0 mt-0.5">{i + 1}</span>
                                    <p className="text-xs text-foreground">{q}</p>
                                  </div>
                                ))}
                              </div>

                              {/* Action choices */}
                              {status === "interested" && (
                                <div className="space-y-2">
                                  <p className="text-[11px] font-bold text-foreground">מה תרצה לעשות?</p>
                                  <div className="flex gap-2 flex-wrap">
                                    <button onClick={() => {
                                      setExpandedTopic(topic.id + "_diy");
                                    }}
                                      className="btn-clay-ghost flex items-center gap-1.5 py-2 px-3 text-[10px]">
                                      <UserCheck className="w-3 h-3" />אעשה לבד
                                    </button>
                                    <button onClick={() => handleHelpRequest(topic)}
                                      className="btn-clay-gold flex items-center gap-1.5 py-2 px-3 text-[10px]">
                                      <HandHelping className="w-3 h-3" />אשמח לעזרה
                                    </button>
                                  </div>
                                </div>
                              )}

                              {/* DIY — set reminder date */}
                              {expandedTopic === topic.id + "_diy" && (
                                <div className="p-3 rounded-xl bg-secondary/40 border border-border/30 space-y-2">
                                  <p className="text-[11px] font-bold text-foreground">מתי תרצה לטפל בזה?</p>
                                  <Input type="date" className="max-w-[200px] text-sm"
                                    value={reminderDate[topic.id] || ""}
                                    onChange={(e) => setReminderDate(prev => ({ ...prev, [topic.id]: e.target.value }))} />
                                  <button onClick={() => handleDIY(topic)}
                                    className="btn-clay-gold py-2 px-4 text-[10px]">
                                    <CalendarDays className="w-3 h-3 inline me-1" />קבע תזכורת
                                  </button>
                                </div>
                              )}

                              {/* Later — pick when */}
                              {status === "later" && (
                                <div className="p-3 rounded-xl bg-secondary/40 border border-border/30 space-y-2">
                                  <p className="text-[11px] font-bold text-foreground">מתי להזכיר?</p>
                                  <div className="flex gap-2 flex-wrap">
                                    {["חודש", "3 חודשים", "6 חודשים"].map((label, i) => {
                                      const months = [1, 3, 6][i];
                                      const d = new Date();
                                      d.setMonth(d.getMonth() + months);
                                      const dateStr = d.toISOString().split("T")[0];
                                      return (
                                        <button key={label} onClick={() => {
                                          setLaterMonth(prev => ({ ...prev, [topic.id]: dateStr }));
                                          handleLater(topic);
                                        }}
                                          className="btn-clay-ghost py-1.5 px-3 text-[10px]">
                                          {label}
                                        </button>
                                      );
                                    })}
                                    <Input type="date" className="max-w-[160px] text-sm h-8"
                                      value={laterMonth[topic.id] || ""}
                                      onChange={(e) => setLaterMonth(prev => ({ ...prev, [topic.id]: e.target.value }))} />
                                    {laterMonth[topic.id] && (
                                      <button onClick={() => handleLater(topic)}
                                        className="btn-clay-gold py-1.5 px-3 text-[10px]">אישור</button>
                                    )}
                                  </div>
                                </div>
                              )}
                            </div>
                          )}

                          {/* Help requested state */}
                          {status === "help_requested" && (
                            <div className="flex items-center gap-2 p-3 rounded-xl bg-emerald-500/5 border border-emerald-500/10">
                              <HandHelping className="w-4 h-4 text-emerald-400" />
                              <span className="text-xs text-emerald-400 font-bold">הבקשה נשלחה — ניצור קשר בקרוב</span>
                            </div>
                          )}

                          {/* DIY state */}
                          {status === "diy" && (
                            <div className="flex items-center gap-2 p-3 rounded-xl bg-blue-500/5 border border-blue-500/10">
                              <UserCheck className="w-4 h-4 text-blue-400" />
                              <span className="text-xs text-blue-400 font-bold">תזכורת נקבעה — בהצלחה!</span>
                              <button onClick={() => updateStatus(topic.id, "claimed")}
                                className="ms-auto text-[10px] text-emerald-400 hover:underline font-bold">סמן כמומש</button>
                            </div>
                          )}

                          {/* Claimed state */}
                          {status === "claimed" && (
                            <span className="flex items-center gap-1.5 py-2 px-3 rounded-xl bg-emerald-500/8 text-emerald-400 text-[10px] font-bold border border-emerald-500/10">
                              <CheckCircle2 className="w-3 h-3" />מומשה
                            </span>
                          )}
                        </div>
                      );
                    })}
                  </motion.div>
                )}
              </AnimatePresence>
            </motion.div>
          );
        })}
      </div>

      {/* Rights Inquiry Form */}
      <motion.div variants={itemVariants}>
        <RightsInquiryForm />
      </motion.div>
    </motion.div>
  );
}
