/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ClientAreaRouteImport } from './routes/client-area'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthenticatedAnalyticsRouteImport } from './routes/_authenticated/analytics'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedDocumentsRouteImport } from './routes/_authenticated/documents'
import { Route as AuthenticatedEntitlementsRouteImport } from './routes/_authenticated/entitlements'
import { Route as AuthenticatedMessagesRouteImport } from './routes/_authenticated/messages'
import { Route as AuthenticatedReferralsRouteImport } from './routes/_authenticated/referrals'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedTasksRouteImport } from './routes/_authenticated/tasks'
import { Route as ClientAreaIndexRouteImport } from './routes/client-area.index'
import { Route as ClientAreaDocumentsRouteImport } from './routes/client-area.documents'
import { Route as ClientAreaEntitlementsRouteImport } from './routes/client-area.entitlements'
import { Route as ClientAreaMessagesRouteImport } from './routes/client-area.messages'
import { Route as AuthenticatedClientsIndexRouteImport } from './routes/_authenticated/clients/index'
import { Route as AuthenticatedClientsIdRouteImport } from './routes/_authenticated/clients/$id'
import { Route as AuthenticatedClientsNewRouteImport } from './routes/_authenticated/clients/new'
import { Route as AuthenticatedPartnerPortalIndexRouteImport } from './routes/_authenticated/partner-portal/index'
import { Route as AuthenticatedPartnerPortalReferralIdRouteImport } from './routes/_authenticated/partner-portal/$referralId'
import { Route as AuthenticatedPartnersIndexRouteImport } from './routes/_authenticated/partners/index'
import { Route as AuthenticatedPartnersIdRouteImport } from './routes/_authenticated/partners/$id'
import { Route as ApiPublicAnalyzePaystubRouteImport } from './routes/api/public/analyze-paystub'
import { Route as ApiPublicNotifyAdminRouteImport } from './routes/api/public/notify-admin'
import { Route as ApiPublicNotifyMessageRouteImport } from './routes/api/public/notify-message'
import { Route as ApiPublicNotifyPartnerRouteImport } from './routes/api/public/notify-partner'
import { Route as ApiPublicNotifySignatureRouteImport } from './routes/api/public/notify-signature'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientAreaRoute = ClientAreaRouteImport.update({
  id: '/client-area',
  path: '/client-area',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAnalyticsRoute = AuthenticatedAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDocumentsRoute = AuthenticatedDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEntitlementsRoute =
  AuthenticatedEntitlementsRouteImport.update({
    id: '/entitlements',
    path: '/entitlements',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMessagesRoute = AuthenticatedMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReferralsRoute = AuthenticatedReferralsRouteImport.update({
  id: '/referrals',
  path: '/referrals',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTasksRoute = AuthenticatedTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ClientAreaIndexRoute = ClientAreaIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ClientAreaRoute,
} as any)
const ClientAreaDocumentsRoute = ClientAreaDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => ClientAreaRoute,
} as any)
const ClientAreaEntitlementsRoute = ClientAreaEntitlementsRouteImport.update({
  id: '/entitlements',
  path: '/entitlements',
  getParentRoute: () => ClientAreaRoute,
} as any)
const ClientAreaMessagesRoute = ClientAreaMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => ClientAreaRoute,
} as any)
const AuthenticatedClientsIndexRoute =
  AuthenticatedClientsIndexRouteImport.update({
    id: '/clients/',
    path: '/clients/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedClientsIdRoute = AuthenticatedClientsIdRouteImport.update({
  id: '/clients/$id',
  path: '/clients/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedClientsNewRoute = AuthenticatedClientsNewRouteImport.update({
  id: '/clients/new',
  path: '/clients/new',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPartnerPortalIndexRoute =
  AuthenticatedPartnerPortalIndexRouteImport.update({
    id: '/partner-portal/',
    path: '/partner-portal/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPartnerPortalReferralIdRoute =
  AuthenticatedPartnerPortalReferralIdRouteImport.update({
    id: '/partner-portal/$referralId',
    path: '/partner-portal/$referralId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPartnersIndexRoute =
  AuthenticatedPartnersIndexRouteImport.update({
    id: '/partners/',
    path: '/partners/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPartnersIdRoute = AuthenticatedPartnersIdRouteImport.update({
  id: '/partners/$id',
  path: '/partners/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiPublicAnalyzePaystubRoute = ApiPublicAnalyzePaystubRouteImport.update({
  id: '/api/public/analyze-paystub',
  path: '/api/public/analyze-paystub',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicNotifyAdminRoute = ApiPublicNotifyAdminRouteImport.update({
  id: '/api/public/notify-admin',
  path: '/api/public/notify-admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicNotifyMessageRoute = ApiPublicNotifyMessageRouteImport.update({
  id: '/api/public/notify-message',
  path: '/api/public/notify-message',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicNotifyPartnerRoute = ApiPublicNotifyPartnerRouteImport.update({
  id: '/api/public/notify-partner',
  path: '/api/public/notify-partner',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicNotifySignatureRoute =
  ApiPublicNotifySignatureRouteImport.update({
    id: '/api/public/notify-signature',
    path: '/api/public/notify-signature',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/client-area': typeof ClientAreaRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/documents': typeof AuthenticatedDocumentsRoute
  '/entitlements': typeof AuthenticatedEntitlementsRoute
  '/messages': typeof AuthenticatedMessagesRoute
  '/referrals': typeof AuthenticatedReferralsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/tasks': typeof AuthenticatedTasksRoute
  '/client-area/documents': typeof ClientAreaDocumentsRoute
  '/client-area/entitlements': typeof ClientAreaEntitlementsRoute
  '/client-area/messages': typeof ClientAreaMessagesRoute
  '/client-area/': typeof ClientAreaIndexRoute
  '/clients/$id': typeof AuthenticatedClientsIdRoute
  '/clients/new': typeof AuthenticatedClientsNewRoute
  '/partner-portal/$referralId': typeof AuthenticatedPartnerPortalReferralIdRoute
  '/partners/$id': typeof AuthenticatedPartnersIdRoute
  '/api/public/analyze-paystub': typeof ApiPublicAnalyzePaystubRoute
  '/api/public/notify-admin': typeof ApiPublicNotifyAdminRoute
  '/api/public/notify-message': typeof ApiPublicNotifyMessageRoute
  '/api/public/notify-partner': typeof ApiPublicNotifyPartnerRoute
  '/api/public/notify-signature': typeof ApiPublicNotifySignatureRoute
  '/clients/': typeof AuthenticatedClientsIndexRoute
  '/partner-portal/': typeof AuthenticatedPartnerPortalIndexRoute
  '/partners/': typeof AuthenticatedPartnersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/documents': typeof AuthenticatedDocumentsRoute
  '/entitlements': typeof AuthenticatedEntitlementsRoute
  '/messages': typeof AuthenticatedMessagesRoute
  '/referrals': typeof AuthenticatedReferralsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/tasks': typeof AuthenticatedTasksRoute
  '/client-area/documents': typeof ClientAreaDocumentsRoute
  '/client-area/entitlements': typeof ClientAreaEntitlementsRoute
  '/client-area/messages': typeof ClientAreaMessagesRoute
  '/client-area': typeof ClientAreaIndexRoute
  '/clients/$id': typeof AuthenticatedClientsIdRoute
  '/clients/new': typeof AuthenticatedClientsNewRoute
  '/partner-portal/$referralId': typeof AuthenticatedPartnerPortalReferralIdRoute
  '/partners/$id': typeof AuthenticatedPartnersIdRoute
  '/api/public/analyze-paystub': typeof ApiPublicAnalyzePaystubRoute
  '/api/public/notify-admin': typeof ApiPublicNotifyAdminRoute
  '/api/public/notify-message': typeof ApiPublicNotifyMessageRoute
  '/api/public/notify-partner': typeof ApiPublicNotifyPartnerRoute
  '/api/public/notify-signature': typeof ApiPublicNotifySignatureRoute
  '/clients': typeof AuthenticatedClientsIndexRoute
  '/partner-portal': typeof AuthenticatedPartnerPortalIndexRoute
  '/partners': typeof AuthenticatedPartnersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/client-area': typeof ClientAreaRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/analytics': typeof AuthenticatedAnalyticsRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/documents': typeof AuthenticatedDocumentsRoute
  '/_authenticated/entitlements': typeof AuthenticatedEntitlementsRoute
  '/_authenticated/messages': typeof AuthenticatedMessagesRoute
  '/_authenticated/referrals': typeof AuthenticatedReferralsRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/tasks': typeof AuthenticatedTasksRoute
  '/client-area/documents': typeof ClientAreaDocumentsRoute
  '/client-area/entitlements': typeof ClientAreaEntitlementsRoute
  '/client-area/messages': typeof ClientAreaMessagesRoute
  '/client-area/': typeof ClientAreaIndexRoute
  '/_authenticated/clients/$id': typeof AuthenticatedClientsIdRoute
  '/_authenticated/clients/new': typeof AuthenticatedClientsNewRoute
  '/_authenticated/partner-portal/$referralId': typeof AuthenticatedPartnerPortalReferralIdRoute
  '/_authenticated/partners/$id': typeof AuthenticatedPartnersIdRoute
  '/api/public/analyze-paystub': typeof ApiPublicAnalyzePaystubRoute
  '/api/public/notify-admin': typeof ApiPublicNotifyAdminRoute
  '/api/public/notify-message': typeof ApiPublicNotifyMessageRoute
  '/api/public/notify-partner': typeof ApiPublicNotifyPartnerRoute
  '/api/public/notify-signature': typeof ApiPublicNotifySignatureRoute
  '/_authenticated/clients/': typeof AuthenticatedClientsIndexRoute
  '/_authenticated/partner-portal/': typeof AuthenticatedPartnerPortalIndexRoute
  '/_authenticated/partners/': typeof AuthenticatedPartnersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/client-area'
    | '/reset-password'
    | '/analytics'
    | '/dashboard'
    | '/documents'
    | '/entitlements'
    | '/messages'
    | '/referrals'
    | '/settings'
    | '/tasks'
    | '/client-area/documents'
    | '/client-area/entitlements'
    | '/client-area/messages'
    | '/client-area/'
    | '/clients/$id'
    | '/clients/new'
    | '/partner-portal/$referralId'
    | '/partners/$id'
    | '/api/public/analyze-paystub'
    | '/api/public/notify-admin'
    | '/api/public/notify-message'
    | '/api/public/notify-partner'
    | '/api/public/notify-signature'
    | '/clients/'
    | '/partner-portal/'
    | '/partners/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/analytics'
    | '/dashboard'
    | '/documents'
    | '/entitlements'
    | '/messages'
    | '/referrals'
    | '/settings'
    | '/tasks'
    | '/client-area/documents'
    | '/client-area/entitlements'
    | '/client-area/messages'
    | '/client-area'
    | '/clients/$id'
    | '/clients/new'
    | '/partner-portal/$referralId'
    | '/partners/$id'
    | '/api/public/analyze-paystub'
    | '/api/public/notify-admin'
    | '/api/public/notify-message'
    | '/api/public/notify-partner'
    | '/api/public/notify-signature'
    | '/clients'
    | '/partner-portal'
    | '/partners'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/client-area'
    | '/reset-password'
    | '/_authenticated/analytics'
    | '/_authenticated/dashboard'
    | '/_authenticated/documents'
    | '/_authenticated/entitlements'
    | '/_authenticated/messages'
    | '/_authenticated/referrals'
    | '/_authenticated/settings'
    | '/_authenticated/tasks'
    | '/client-area/documents'
    | '/client-area/entitlements'
    | '/client-area/messages'
    | '/client-area/'
    | '/_authenticated/clients/$id'
    | '/_authenticated/clients/new'
    | '/_authenticated/partner-portal/$referralId'
    | '/_authenticated/partners/$id'
    | '/api/public/analyze-paystub'
    | '/api/public/notify-admin'
    | '/api/public/notify-message'
    | '/api/public/notify-partner'
    | '/api/public/notify-signature'
    | '/_authenticated/clients/'
    | '/_authenticated/partner-portal/'
    | '/_authenticated/partners/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ClientAreaRoute: typeof ClientAreaRouteWithChildren
  ResetPasswordRoute: typeof ResetPasswordRoute
  ApiPublicAnalyzePaystubRoute: typeof ApiPublicAnalyzePaystubRoute
  ApiPublicNotifyAdminRoute: typeof ApiPublicNotifyAdminRoute
  ApiPublicNotifyMessageRoute: typeof ApiPublicNotifyMessageRoute
  ApiPublicNotifyPartnerRoute: typeof ApiPublicNotifyPartnerRoute
  ApiPublicNotifySignatureRoute: typeof ApiPublicNotifySignatureRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/client-area': {
      id: '/client-area'
      path: '/client-area'
      fullPath: '/client-area'
      preLoaderRoute: typeof ClientAreaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/analytics': {
      id: '/_authenticated/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AuthenticatedAnalyticsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/documents': {
      id: '/_authenticated/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof AuthenticatedDocumentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/entitlements': {
      id: '/_authenticated/entitlements'
      path: '/entitlements'
      fullPath: '/entitlements'
      preLoaderRoute: typeof AuthenticatedEntitlementsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/messages': {
      id: '/_authenticated/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof AuthenticatedMessagesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/referrals': {
      id: '/_authenticated/referrals'
      path: '/referrals'
      fullPath: '/referrals'
      preLoaderRoute: typeof AuthenticatedReferralsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tasks': {
      id: '/_authenticated/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof AuthenticatedTasksRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/client-area/': {
      id: '/client-area/'
      path: '/'
      fullPath: '/client-area/'
      preLoaderRoute: typeof ClientAreaIndexRouteImport
      parentRoute: typeof ClientAreaRoute
    }
    '/client-area/documents': {
      id: '/client-area/documents'
      path: '/documents'
      fullPath: '/client-area/documents'
      preLoaderRoute: typeof ClientAreaDocumentsRouteImport
      parentRoute: typeof ClientAreaRoute
    }
    '/client-area/entitlements': {
      id: '/client-area/entitlements'
      path: '/entitlements'
      fullPath: '/client-area/entitlements'
      preLoaderRoute: typeof ClientAreaEntitlementsRouteImport
      parentRoute: typeof ClientAreaRoute
    }
    '/client-area/messages': {
      id: '/client-area/messages'
      path: '/messages'
      fullPath: '/client-area/messages'
      preLoaderRoute: typeof ClientAreaMessagesRouteImport
      parentRoute: typeof ClientAreaRoute
    }
    '/_authenticated/clients/': {
      id: '/_authenticated/clients/'
      path: '/clients'
      fullPath: '/clients/'
      preLoaderRoute: typeof AuthenticatedClientsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/clients/$id': {
      id: '/_authenticated/clients/$id'
      path: '/clients/$id'
      fullPath: '/clients/$id'
      preLoaderRoute: typeof AuthenticatedClientsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/clients/new': {
      id: '/_authenticated/clients/new'
      path: '/clients/new'
      fullPath: '/clients/new'
      preLoaderRoute: typeof AuthenticatedClientsNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/partner-portal/': {
      id: '/_authenticated/partner-portal/'
      path: '/partner-portal'
      fullPath: '/partner-portal/'
      preLoaderRoute: typeof AuthenticatedPartnerPortalIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/partner-portal/$referralId': {
      id: '/_authenticated/partner-portal/$referralId'
      path: '/partner-portal/$referralId'
      fullPath: '/partner-portal/$referralId'
      preLoaderRoute: typeof AuthenticatedPartnerPortalReferralIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/partners/': {
      id: '/_authenticated/partners/'
      path: '/partners'
      fullPath: '/partners/'
      preLoaderRoute: typeof AuthenticatedPartnersIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/partners/$id': {
      id: '/_authenticated/partners/$id'
      path: '/partners/$id'
      fullPath: '/partners/$id'
      preLoaderRoute: typeof AuthenticatedPartnersIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/analyze-paystub': {
      id: '/api/public/analyze-paystub'
      path: '/api/public/analyze-paystub'
      fullPath: '/api/public/analyze-paystub'
      preLoaderRoute: typeof ApiPublicAnalyzePaystubRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/notify-admin': {
      id: '/api/public/notify-admin'
      path: '/api/public/notify-admin'
      fullPath: '/api/public/notify-admin'
      preLoaderRoute: typeof ApiPublicNotifyAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/notify-message': {
      id: '/api/public/notify-message'
      path: '/api/public/notify-message'
      fullPath: '/api/public/notify-message'
      preLoaderRoute: typeof ApiPublicNotifyMessageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/notify-partner': {
      id: '/api/public/notify-partner'
      path: '/api/public/notify-partner'
      fullPath: '/api/public/notify-partner'
      preLoaderRoute: typeof ApiPublicNotifyPartnerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/notify-signature': {
      id: '/api/public/notify-signature'
      path: '/api/public/notify-signature'
      fullPath: '/api/public/notify-signature'
      preLoaderRoute: typeof ApiPublicNotifySignatureRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAnalyticsRoute: typeof AuthenticatedAnalyticsRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDocumentsRoute: typeof AuthenticatedDocumentsRoute
  AuthenticatedEntitlementsRoute: typeof AuthenticatedEntitlementsRoute
  AuthenticatedMessagesRoute: typeof AuthenticatedMessagesRoute
  AuthenticatedReferralsRoute: typeof AuthenticatedReferralsRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedTasksRoute: typeof AuthenticatedTasksRoute
  AuthenticatedClientsIdRoute: typeof AuthenticatedClientsIdRoute
  AuthenticatedClientsNewRoute: typeof AuthenticatedClientsNewRoute
  AuthenticatedPartnerPortalReferralIdRoute: typeof AuthenticatedPartnerPortalReferralIdRoute
  AuthenticatedPartnersIdRoute: typeof AuthenticatedPartnersIdRoute
  AuthenticatedClientsIndexRoute: typeof AuthenticatedClientsIndexRoute
  AuthenticatedPartnerPortalIndexRoute: typeof AuthenticatedPartnerPortalIndexRoute
  AuthenticatedPartnersIndexRoute: typeof AuthenticatedPartnersIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAnalyticsRoute: AuthenticatedAnalyticsRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDocumentsRoute: AuthenticatedDocumentsRoute,
  AuthenticatedEntitlementsRoute: AuthenticatedEntitlementsRoute,
  AuthenticatedMessagesRoute: AuthenticatedMessagesRoute,
  AuthenticatedReferralsRoute: AuthenticatedReferralsRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedTasksRoute: AuthenticatedTasksRoute,
  AuthenticatedClientsIdRoute: AuthenticatedClientsIdRoute,
  AuthenticatedClientsNewRoute: AuthenticatedClientsNewRoute,
  AuthenticatedPartnerPortalReferralIdRoute:
    AuthenticatedPartnerPortalReferralIdRoute,
  AuthenticatedPartnersIdRoute: AuthenticatedPartnersIdRoute,
  AuthenticatedClientsIndexRoute: AuthenticatedClientsIndexRoute,
  AuthenticatedPartnerPortalIndexRoute: AuthenticatedPartnerPortalIndexRoute,
  AuthenticatedPartnersIndexRoute: AuthenticatedPartnersIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface ClientAreaRouteChildren {
  ClientAreaDocumentsRoute: typeof ClientAreaDocumentsRoute
  ClientAreaEntitlementsRoute: typeof ClientAreaEntitlementsRoute
  ClientAreaMessagesRoute: typeof ClientAreaMessagesRoute
  ClientAreaIndexRoute: typeof ClientAreaIndexRoute
}

const ClientAreaRouteChildren: ClientAreaRouteChildren = {
  ClientAreaDocumentsRoute: ClientAreaDocumentsRoute,
  ClientAreaEntitlementsRoute: ClientAreaEntitlementsRoute,
  ClientAreaMessagesRoute: ClientAreaMessagesRoute,
  ClientAreaIndexRoute: ClientAreaIndexRoute,
}

const ClientAreaRouteWithChildren = ClientAreaRoute._addFileChildren(
  ClientAreaRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ClientAreaRoute: ClientAreaRouteWithChildren,
  ResetPasswordRoute: ResetPasswordRoute,
  ApiPublicAnalyzePaystubRoute: ApiPublicAnalyzePaystubRoute,
  ApiPublicNotifyAdminRoute: ApiPublicNotifyAdminRoute,
  ApiPublicNotifyMessageRoute: ApiPublicNotifyMessageRoute,
  ApiPublicNotifyPartnerRoute: ApiPublicNotifyPartnerRoute,
  ApiPublicNotifySignatureRoute: ApiPublicNotifySignatureRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
