-- more30 · 32 nadlan-berega — backfill missing table creation for 4 live-only tables
-- ============================================================================
-- BACKFILL NOTICE: these tables exist live on nadlan (report_exports: 22 rows,
-- saved_reports: 19 rows, saved_report_versions: 141 rows, tabu_documents: 0
-- rows) but were never captured by any migration file in this repo -- unlike
-- nadlan_pro, whose live-only migrations were already backfilled in 2a6a9fcf
-- (0126-0135). A fresh environment built from this repo's migrations alone
-- would be missing all four; lib/savedreports.ts, lib/requests.ts (tabu*) and
-- lib/store.ts (logExport) all reference them today.
--
-- All four are correctly RLS-enabled with ZERO policies (confirmed live via
-- get_advisors' rls_enabled_no_policy check) -- this is intentional, not a
-- gap to fix: every access in the app goes through the service-role key
-- (SUPABASE_SERVICE_KEY / SUPABASE_SERVICE_ROLE_KEY in lib/store.ts,
-- lib/savedreports.ts, lib/requests.ts), which bypasses RLS entirely, so no
-- anon/authenticated policy is needed or wanted. This migration reproduces
-- that as-built state exactly (including the anon/authenticated GRANTs that
-- exist live on report_exports/tabu_documents but not on saved_reports/
-- saved_report_versions -- harmless either way since RLS with no policy
-- blocks all non-service-role access regardless of GRANTs, but kept faithful
-- to live rather than "cleaned up" to avoid any behavior drift).
-- ============================================================================

create table if not exists nadlan.saved_reports (
  id uuid primary key default gen_random_uuid(),
  slug text not null unique,
  property_key text not null unique,
  gush text,
  helka text,
  tat_helka text,
  city text,
  street text,
  house_num text,
  entrance text,
  floor text,
  apartment text,
  asset_type text not null default 'residential',
  best_tier text not null default 'basic',
  headline text,
  lat double precision,
  lng double precision,
  itm_x double precision,
  itm_y double precision,
  report jsonb,
  generations integer not null default 1,
  views integer not null default 0,
  first_seen_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists saved_reports_gush_helka_idx on nadlan.saved_reports (gush, helka);
create index if not exists saved_reports_updated_idx on nadlan.saved_reports (updated_at desc);

alter table nadlan.saved_reports enable row level security;

create table if not exists nadlan.saved_report_versions (
  id uuid primary key default gen_random_uuid(),
  saved_report_id uuid not null references nadlan.saved_reports(id) on delete cascade,
  tier text not null,
  asset_type text not null,
  report jsonb not null,
  created_at timestamptz not null default now()
);

create index if not exists saved_report_versions_parent_idx
  on nadlan.saved_report_versions (saved_report_id, created_at desc);

alter table nadlan.saved_report_versions enable row level security;

create table if not exists nadlan.report_exports (
  id bigint generated by default as identity primary key,
  property_id bigint references nadlan.properties(id) on delete set null,
  report_type text,
  selected_layers jsonb,
  created_at timestamptz default now()
);

create index if not exists report_exports_property_id_idx on nadlan.report_exports (property_id);

alter table nadlan.report_exports enable row level security;

create table if not exists nadlan.tabu_documents (
  id bigint generated always as identity primary key,
  request_id bigint references nadlan.report_requests(id) on delete set null,
  gush text,
  helka text,
  tat_helka text,
  address text,
  scope text not null default 'apartment'
    check (scope in ('apartment', 'entrance', 'building')),
  entrance text,
  apartment text,
  doc_type text default 'regular'
    check (doc_type in ('regular', 'historical', 'concentrated')),
  file_name text,
  file_path text,
  mime_type text,
  size_bytes bigint,
  uploaded_at timestamptz not null default now(),
  uploaded_by text,
  analysis_status text not null default 'none'
    check (analysis_status in ('none', 'running', 'done', 'failed')),
  analysis jsonb,
  analysis_error text,
  analyzed_at timestamptz,
  raw_text text,
  created_at timestamptz not null default now()
);

create index if not exists tabu_documents_parcel_idx on nadlan.tabu_documents (gush, helka);
create index if not exists tabu_documents_request_idx on nadlan.tabu_documents (request_id);

alter table nadlan.tabu_documents enable row level security;

-- Matches the live grant set exactly (verified via information_schema.role_table_grants):
-- report_exports/tabu_documents also carry anon+authenticated grants (harmless dead
-- grants under RLS-with-no-policy), saved_reports/saved_report_versions carry only
-- service_role. Not normalized to avoid any behavior drift from what is live today.
grant select, insert, update, delete, references, trigger, truncate
  on nadlan.report_exports, nadlan.tabu_documents
  to anon, authenticated, service_role;

grant select, insert, update, delete, references, trigger, truncate
  on nadlan.saved_reports, nadlan.saved_report_versions
  to service_role;
