ALTER TABLE public.budget_items
  ADD COLUMN IF NOT EXISTS start_date date DEFAULT CURRENT_DATE,
  ADD COLUMN IF NOT EXISTS duration_months integer DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS end_date date DEFAULT NULL;